project_id = "xjuucrjxoiyojtanyjyq"

[functions.session]
verify_jwt = false

[functions.orders]
verify_jwt = false

[functions.deposits]  
verify_jwt = false

[functions.zkp2p-proxy]
verify_jwt = false