// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xjuucrjxoiyojtanyjyq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhqdXVjcmp4b2l5b2p0YW55anlxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4MzgzNjEsImV4cCI6MjA3MjQxNDM2MX0.e6s8jQrH5fgC_OyF1lXaPGPsHfH9_2u2HgS6u9Wn3g8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});